version: '3.7'

services:
  neo4j:
    image: neo4j:enterprise
    container_name: neo4j
    restart: unless-stopped
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes