name: workspace

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: 'admin@password'
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - pihole_data:/etc/pihole

volumes:
  pihole_data:
