services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    hostname: linkding
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - data:/etc/linkding/data"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data:
