version: '3.7'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - "8080:80"